web:
 image: nginx:latest
 ports:
 - "80:80"
 volumes:
 - ./code:/code
 - default.conf:/etc/nginx/conf.d/default.conf
 links:
 - php
 - mymysql
php:
 image: php:7-fpm
 volumes:
 - ./code:/code
mymysql:
 image: mysql
 container_name: mysql
 environment:
 - MYSQL_DATABASE=db
 - MYSQL_ROOT_PASSWORD=RAPtor1234
 - MYSQL_USER=admin
 - MYSQL_PASSWORD=admin
 ports:
 - 3306:3306
